<?

$arTests = array(
	array(
		'NAME' => 'Ошибка в url',
		'VAR' => '',
		'METHOD' => 'GET',
		'URI' => '/url',
		'DATA' => '',
		'NEED' => 404,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Авторизация по телефону',
		'VAR' => 'пользователь заблокирован',
		'METHOD' => 'POST',
		'URI' => '/auth/phone',
		'DATA' => '{"phone":"79171111111"}',
		'NEED' => 403,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Авторизация по телефону',
		'VAR' => 'не задан телефон',
		'METHOD' => 'POST',
		'URI' => '/auth/phone',
		'DATA' => '{}',
		'NEED' => 400,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Авторизация по телефону',
		'VAR' => 'ошибка в формате',
		'METHOD' => 'POST',
		'URI' => '/auth/phone',
		'DATA' => '{"phone":"9170010203"}',
		'NEED' => 400,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Авторизация по телефону',
		'VAR' => '',
		'METHOD' => 'POST',
		'URI' => '/auth/phone',
		'DATA' => '{"phone":"79170010203"}',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Ввод кода из sms',
		'VAR' => 'Неправильный код',
		'METHOD' => 'POST',
		'URI' => '/auth/verify',
		'DATA' => '{"phone":"79170010203","code":"0001","user":0,"device":{"uuid":"0a89df6v7df6sv7r6s07f","x":320,"y":480}}',
		'NEED' => 400,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Ввод кода из sms',
		'VAR' => 'Неправильный id пользователя',
		'METHOD' => 'POST',
		'URI' => '/auth/verify',
		'DATA' => '{"phone":"79170010203","code":"0001","user":0,"device":{"uuid":"0a89df6v7df6sv7r6s07f","x":320,"y":480}}',
		'NEED' => 400,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Ввод кода из sms',
		'VAR' => '',
		'METHOD' => 'POST',
		'URI' => '/auth/verify',
		'DATA' => '{"phone":"79170010203","code":"0001","user":0,"device":{"uuid":"0a89df6v7df6sv7r6s07f","x":320,"y":480}}',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'FAQ',
		'VAR' => '',
		'METHOD' => 'GET',
		'URI' => '/faq',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Состояния (товара)',
		'VAR' => '',
		'METHOD' => 'GET',
		'URI' => '/catalog/condition',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Цвета',
		'VAR' => '',
		'METHOD' => 'GET',
		'URI' => '/catalog/color',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Разделы каталога',
		'VAR' => '',
		'METHOD' => 'GET',
		'URI' => '/catalog/section',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Размеры',
		'VAR' => 'для указанного раздела',
		'METHOD' => 'GET',
		'URI' => '/catalog/size/16',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Размеры',
		'VAR' => 'несуществующий раздел',
		'METHOD' => 'GET',
		'URI' => '/catalog/size/1',
		'DATA' => '',
		'NEED' => 404,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Размеры',
		'VAR' => 'раздел без размеров',
		'METHOD' => 'GET',
		'URI' => '/catalog/size/13',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Способы оплаты',
		'VAR' => '',
		'METHOD' => 'GET',
		'URI' => '/catalog/payment',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Способы отправки',
		'VAR' => '',
		'METHOD' => 'GET',
		'URI' => '/catalog/delivery',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Бренды',
		'VAR' => '',
		'METHOD' => 'GET',
		'URI' => '/catalog/brand',
		'DATA' => '',
		'NEED' => 200,
		'AUTH' => '',
	),
	array(
		'NAME' => 'Добавление бренда',
		'VAR' => 'Ошибка авторизации',
		'METHOD' => 'POST',
		'URI' => '/catalog/addbrand',
		'DATA' => '{"name":"Новый бренд"}',
		'NEED' => 401,
		'AUTH' => 'd34a628abc31',
	),
	array(
		'NAME' => 'Добавление бренда',
		'VAR' => 'Не задано название',
		'METHOD' => 'POST',
		'URI' => '/catalog/addbrand',
		'DATA' => '{"name":""}',
		'NEED' => 400,
		'AUTH' => 'x',
	),
	array(
		'NAME' => 'Добавление бренда',
		'VAR' => 'Уже есть',
		'METHOD' => 'POST',
		'URI' => '/catalog/addbrand',
		'DATA' => '{"name":"Versace"}',
		'NEED' => 400,
		'AUTH' => 'x',
	),
	array(
		'NAME' => 'Добавление бренда',
		'VAR' => '',
		'METHOD' => 'POST',
		'URI' => '/catalog/addbrand',
		'DATA' => '{"name":"Новый бренд"}',
		'NEED' => 200,
		'AUTH' => 'x',
	),
	array(
		'NAME' => 'Добавление объявления',
		'VAR' => 'Ошибка авторизации',
		'METHOD' => 'POST',
		'URI' => '/ad/add',
		'DATA' => '',
		'NEED' => 401,
	    'AUTH' => 'd34a628abc31',
	),
	array(
		'NAME' => 'Добавление объявления',
		'VAR' => 'Ошибки в данных',
		'METHOD' => 'POST',
		'URI' => '/ad/add',
		'DATA' => '{"section":0,"brand":0,"condition":0,"color":0,"size":0,"material":"","features":"","purchase":0,"price":0,"payment":[""],"delivery":{}',
		'NEED' => 400,
		'AUTH' => 'x',
	),
	array(
		'NAME' => 'Добавление объявления',
		'VAR' => '+ файл',
		'METHOD' => 'POST',
		'URI' => '/ad/add',
		'DATA' => '{"section":17,"brand":474,"condition":13,"color":15,"size":65,"material":"кожа","features":"2 раза носил","purchase":20000,"price":10000,"payment":["agreement","application"],"delivery":{"personal":0,"courier":500,"post":400}}',
		'NEED' => 200,
		'AUTH' => 'x',
	),
);